#!/bin/bash
# Default options
DIR="."
BETA=false

# Usage
USAGE="Usage: $0 [-b|--beta] [PATH]"

# Parse arguments
while [ $# -gt 0 ]
do
  key="$1"
  case $key in
    -h|--help)
    echo "$USAGE"
    exit
    ;;
    -b|--beta)
    BETA=true
    shift
    ;;
    *)
    if [ $# -eq 1 ]; then
      DIR=$key
      shift
    else
      echo "$USAGE"
      exit 1
    fi
    ;;
  esac
done
shopt -s nullglob

FOUND=0
if [ $BETA = false ]; then
  APP="Xcode"
else
  APP="Xcode-beta"
fi

# Try to open the first xcworkspace file found
EXT='xcworkspace'
for i in $DIR/*.$EXT; do
  open -a $APP "$i"
  FOUND=1
  break
done

# If nothing was found, try to open the first xcodeproj file found
if [ $FOUND -eq 0 ]; then
  EXT='xcodeproj'
  for i in $DIR/*.$EXT; do
    open -a $APP "$i"
    FOUND=1
    break
  done
fi

shopt -u nullglob

# Print message if nothing was found
if [ $FOUND -eq 0 ]; then
  echo "No xcworkspace/xcodeproj file found in the specified directory."
  exit 1
fi
