#!/bin/bash
EXT='xcworkspace'

DIR=${1:-.} # DIR is either the first argument or the current directory

shopt -s nullglob

found=0
for i in ${DIR}/*.${EXT}; do
    open -a Xcode "$i"
    found=1
    break
done
[ $found -eq 0 ] && echo "No Xcode workspace found"

shopt -u nullglob

